base_url: "https://webscraper.io/test-sites/e-commerce/more"
category: "computers/laptops"

selectors:
  card: ".card"
  load_more_button: ".ecomerce-items-scroll-more"
  title: ".title"
  price: ".price"
  description: ".description"
  ratings_container: ".ratings"
  star_icon: ".ws-icon-star"
  reviews: ".ratings p.pull-right"

currency:
  default: "USD"
  target: "EUR"
  rates:
    USD: 1.0
    EUR: 0.85
    GBP: 0.75
    JPY: 110.0
    CAD: 1.25

output:
  csv_filename: "products.csv"
  json_filename: "products.json"
  raw_csv_filename: "products_raw.csv"
  raw_json_filename: "products_raw.json"
  failed_json_filename: "failed_products.json"

logging:
  level: "INFO"
  format: "json"
  file: "scraper.log"
  console: true
